version: "3.3"
services:
#  webapp:
#    build:
#      context: ./auth
#    ports:
#      - "8085:8080"
#    depends_on:
#      - mysql-usu
#      - mysql-rest
#      - rabbitmq
#    volumes:
#       - ./auth/target/auth*.jar:/app/auth.jar
  mysql-usu:
    image: mysql:5
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=usuario
    volumes:
      - db-usu:/var/lib/mysql
  mysql-rest:
    image: mysql:5
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=restaurante
    volumes:
      - db-rest:/var/lib/mysql
  mysql-ped:
    image: mysql:5
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=pedido
    volumes:
      - db-ped:/var/lib/mysql
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
volumes:
  db-usu:
  db-rest:
  db-ped:
